- name: sol validator setup
  become: true
  become_user: solana
  copy:
    src: validator.sh
    dest: /home/solana/validator.sh
    owner: solana
    group: solana
    mode: "0755"

- name: setup sol.service
  become: true
  become_user: root
  copy:
    src: sol.service
    dest: /etc/systemd/system/sol.service
    owner: root
    group: root
    mode: "0755"

- name: copy restart.sh
  become: true
  become_user: solana
  copy:
    src: restart.sh
    dest: /home/solana/restart.sh
    owner: solana
    group: solana
    mode: "0755"
    
- name: copy download_start.sh
  become: true
  become_user: solana
  copy:
    src: download_start.sh
    dest: /home/solana/download_start.sh
    owner: solana
    group: solana
    mode: "0755"

- name: copy snapcheck.py
  become: true
  become_user: solana
  copy:
    src: snapcheck.py
    dest: /mnt/snapcheck.py
    owner: solana
    group: solana

- name: copy snapshot-finder.py
  become: true
  become_user: solana
  copy:
    src: snapshot-finder.py
    dest: /mnt/snapshot-finder.py
    owner: solana
    group: solana

- name: copy montip.py
  become: true
  become_user: solana
  copy:
    src: montip.py
    dest: /mnt/montip.py
    owner: solana
    group: solana

