- name: solana repository
  become: true
  become_user: solana
  git:
    repo: "https://github.com/solana-labs/solana.git"
    dest: /mnt/solana
    version: tags/v{{ solana_version }}

- name: build solana
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && cargo build --release
  args:
    chdir: /mnt/solana
    executable: /bin/bash
