#- name: check key file exists
#  stat:
#    path: "{{ identity_keypair_location }}"
#  register: keyfile
#  failed_when: not keyfile.stat.exists

- name: check disks exist
  become: true
  become_user: root
  shell: fdisk -l | grep 'Disk /dev/{{ ledger_disk }}'
  when: setup_disks is defined and (setup_disks | bool)

- name: validate some variables
  assert:
    that:
      - ((ramdisk_size is defined) and (ansible_memtotal_mb >= 1500*ramdisk_size) or ramdisk_size is not defined)
    msg: machine ram is too low for ram diskq. comment out ramdisk_size in defaults/main.yml
